services:
  - type: web
    name: your-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # or any entry script like your main Flask file
    envVars:
      - key: FLASK_ENV
        value: "production"
    python_version: 3.8   # Choose Python 3.8 or the version compatible with Rasa
